name: dart_notcurses
description: Dart bindings for NotCurses
version: 0.0.1
repository: https://github.com/kascote/dart_notcurses
homepage: https://github.com/kascote/dart_notcurses


environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  characters: ^1.2.0

dev_dependencies:
  lints: ^1.0.0
  ffigen: ^4.1.2
